-- which-key helps you remember key bindings by showing a popup
-- with the active keybindings of the command you started typing.
return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    plugins = { spelling = true },
    spec = {
      mode = { 'n', 'v' },
      { 'cc', group = 'comment' },
      { 'g', group = '+goto' },
      { 'gs', group = '+surround' },
      -- { 'x', group = '+comment' },
      { ']', group = '+next' },
      { '[', group = '+prev' },
      { '<leader>b', group = '+buffer' },
      { '<leader>c', group = '+code' },
      { '<leader>cp', group = '+copilot' },
      { '<leader>cpC', group = '+copilot chat' },
      { '<leader>d', group = '+debug' },
      { '<leader>d', group = '+diagnostics/quickfix' },
      { '<leader>E', group = '+editor' },
      { '<leader>f', group = '+find' },
      { '<leader>g', group = '+git' },
      { '<leader>gh', group = '+hunks' },
      { '<leader>h', group = '+harpoon' },
      { '<leader>i', group = '+insert' },
      { '<leader>ip', group = '+print debug' },
      { '<leader>ips', group = '+surround' },
      { '<leader>is', group = '+separator' },
      { '<leader>M', group = '+misc' },
      { '<leader>Md', group = '+duck' },
      { '<leader>Mf', group = '+fuck' },
      { '<leader>Mfm', group = '+my' },
      { '<leader>Mh', group = '+hack' },
      { '<leader>Mo', group = '+ooh' },
      { '<leader>Mow', group = '+wah' },
      { '<leader>Mowa', group = '+ah' },
      { '<leader>Mowaa', group = '+ah' },
      { '<leader>Mowaaa', desc = 'ah' },
      { '<leader>Mp', group = '+pets' },
      { '<leader>O', group = '+options' },
      { '<leader>p', group = '+plugins' },
      { '<leader>s', group = '+search' },
      { '<leader>sr', group = '+replace' },
      { '<leader>S', group = '+session' },
      { '<leader>sn', group = '+neovim' },
      { '<leader>sN', group = '+noice' },
      { '<leader>u', group = '+ui' },
      { '<leader>w', group = '+windows' },
      { '<leader>y', group = '+yank' },
    },
    icons = {
      -- set icon mappings to true if you have a Nerd Font
      mappings = vim.g.have_nerd_font,
      -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
      -- default which-key.nvim defined Nerd Font icons, otherwise define a string table
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
  },
}
